README.md, pom.xml, src/main/java/com/flowingcode/vaadin/addons/gridexporter/DocxInputStreamFactory.java, src/main/java/com/flowingcode/vaadin/addons/gridexporter/ExcelInputStreamFactory.java, src/main/java/com/flowingcode/vaadin/addons/gridexporter/PdfInputStreamFactory.java, src/main/java/com/flowingcode/vaadin/addons/gridexporter/PoiHelper.java
This PR allows the exporter to partially work with older Apache POI versions by creating a PoiHelper that will try to use different methods with reflection. Tested with Apache POI 3.15 and the latest version.
=> Old poi support

pom.xml
=> fix: fix NPE when the grid to export does not contain a footer row

src/main/java/com/flowingcode/vaadin/addons/gridexporter/BaseInputStreamFactory.java, src/main/java/com/flowingcode/vaadin/addons/gridexporter/CsvInputStreamFactory.java, src/main/java/com/flowingcode/vaadin/addons/gridexporter/DocxInputStreamFactory.java, src/main/java/com/flowingcode/vaadin/addons/gridexporter/ExcelInputStreamFactory.java, src/test/java/com/flowingcode/vaadin/addons/gridexporter/GridExporterCustomTemplateDemo.java
=> feat: implement cell alignment based on grid's column text alignment

src/test/java/com/flowingcode/vaadin/addons/gridexporter/test/LayoutTest.java
Let's ignore this test while we are refactoring the demos. We should consider moving it to the demos project.
=> chore: ignore LayoutTest

README.md
=> Clarify that the exporter has to be created before attaching the grid

src/main/java/com/flowingcode/vaadin/addons/gridexporter/CsvInputStreamFactory.java
=> fix: check if grid has footer on csv export

src/main/java/com/flowingcode/vaadin/addons/gridexporter/CsvInputStreamFactory.java
=> fix: extract Grid data in main thread to avoid UI locking issues

src/main/java/com/flowingcode/vaadin/addons/gridexporter/BaseInputStreamFactory.java
=> fix: fix ClassCastException when exporting

pom.xml
=> [1.x] build: upgrade grid-helpers to 1.1.1

src/main/java/com/flowingcode/vaadin/addons/gridexporter/BaseInputStreamFactory.java, src/main/java/com/flowingcode/vaadin/addons/gridexporter/GridExporter.java, src/test/java/com/flowingcode/vaadin/addons/gridexporter/GridExporterDemoView.java, src/test/java/com/flowingcode/vaadin/addons/gridexporter/GridExporterHierarchicalDataDemo.java, src/test/java/com/flowingcode/vaadin/addons/gridexporter/PersonTreeEntry.java
Hi there,
we started using your addon to implement an Excel-Export. Sadly we use a TreeGrid and thus an extension of Vaadin's `HierarchicalDataProvider` that didn't work with your addon.
So I simply added the support for `HierarchicalDataProvider` in your code and wanted to share that code with you by creating this PullRequest, hoping that this extension will find the way into one of the upcoming releases ;)
I added a new Demo that uses a TreeGrid to show the generated Person Objects grouped by their age.
Best regards!
=> Support hierarchical dataprovider

src/main/java/com/flowingcode/vaadin/addons/gridexporter/ExcelInputStreamFactory.java, src/test/java/com/flowingcode/vaadin/addons/gridexporter/GridExporterBigDatasetDemo.java, src/test/java/com/flowingcode/vaadin/addons/gridexporter/GridExporterDemoView.java
=> Fix Issue 82

src/main/java/com/flowingcode/vaadin/addons/gridexporter/ExcelInputStreamFactory.java
=> Fix missing last row when exporting Excel file

pom.xml, src/main/java/com/flowingcode/vaadin/addons/gridexporter/FooterToolbar.java, src/main/java/com/flowingcode/vaadin/addons/gridexporter/FooterToolbarItem.java, src/main/java/com/flowingcode/vaadin/addons/gridexporter/FooterToolbarItemPosition.java, src/main/java/com/flowingcode/vaadin/addons/gridexporter/GridExporter.java, src/test/java/com/flowingcode/vaadin/addons/gridexporter/GridExporterDemo.java
=> Add support to add components to footer toolbar

src/main/java/com/flowingcode/vaadin/addons/gridexporter/ExcelInputStreamFactory.java
Backport of [this PR](https://github.com/FlowingCode/GridExporterAddon/pull/88) that fixes [this issue](https://github.com/FlowingCode/GridExporterAddon/issues/87)
=> fix: reuse cell style (backport #88)

pom.xml, src/main/java/com/flowingcode/vaadin/addons/gridexporter/ExcelInputStreamFactory.java, src/main/java/com/flowingcode/vaadin/addons/gridexporter/GridExporter.java, src/test/java/com/flowingcode/vaadin/addons/gridexporter/GridExporterSimpleCustomTemplateDemo.java
Saves cellstyles in an internal map to optimize the usage of them, depending on the format.
Closes #93
=> Add support for providing excel formats per cell

pom.xml, src/main/java/com/flowingcode/vaadin/addons/gridexporter/ExcelInputStreamFactory.java, src/main/java/com/flowingcode/vaadin/addons/gridexporter/GridExporter.java, src/test/java/com/flowingcode/vaadin/addons/gridexporter/GridExporterSimpleCustomTemplateDemo.java
Closes issue #93 in v23 version
=> Backport of #97

src/main/java/com/flowingcode/vaadin/addons/gridexporter/ExcelInputStreamFactory.java
=> fix: clear column cellstyle info before starting the export

src/main/java/com/flowingcode/vaadin/addons/gridexporter/ExcelInputStreamFactory.java
=> backport of #101

src/test/java/com/flowingcode/vaadin/addons/gridexporter/FakerInstance.java, src/test/java/com/flowingcode/vaadin/addons/gridexporter/GridExporterBigDatasetDemo.java, src/test/java/com/flowingcode/vaadin/addons/gridexporter/GridExporterCustomColumnsDemo.java, src/test/java/com/flowingcode/vaadin/addons/gridexporter/GridExporterCustomLinkDemo.java, src/test/java/com/flowingcode/vaadin/addons/gridexporter/GridExporterCustomTemplateDemo.java, src/test/java/com/flowingcode/vaadin/addons/gridexporter/GridExporterDemo.java, src/test/java/com/flowingcode/vaadin/addons/gridexporter/GridExporterHierarchicalDataDemo.java, src/test/java/com/flowingcode/vaadin/addons/gridexporter/GridExporterSimpleCustomTemplateDemo.java
=> perf(demo): initialize Faker as singleton

src/main/java/com/flowingcode/vaadin/addons/gridexporter/ExcelInputStreamFactory.java, src/test/java/com/flowingcode/vaadin/addons/gridexporter/GridExporterDemo.java
=> Backport 105 fix

pom.xml
=> build: upgrade font-awesome to 5.2.2

src/main/java/com/flowingcode/vaadin/addons/gridexporter/BaseStreamResourceWriter.java, src/main/java/com/flowingcode/vaadin/addons/gridexporter/DocxStreamResourceWriter.java, src/main/java/com/flowingcode/vaadin/addons/gridexporter/ExcelStreamResourceWriter.java, src/test/java/com/flowingcode/vaadin/addons/gridexporter/GridExporterDemoView.java, src/test/java/com/flowingcode/vaadin/addons/gridexporter/GridExporterMultipleHeaderRowsDemo.java
Add support for multiple header rows only for excel files
=> feat: add support for multiple header rows

src/main/java/com/flowingcode/vaadin/addons/gridexporter/BaseStreamResourceWriter.java
=> fix: avoid returning nulls to prevent later NPE

src/main/java/com/flowingcode/vaadin/addons/gridexporter/GridExporter.java
=> [1.x] fix: prioritize custom value provider when extracting column values
